In [242]:
import numpy as np 
import matplotlib.pyplot as plt
from scipy.io import loadmat
X=loadmat("mnist.mat")
data_train=X['trainX']
print(data_train.shape)
data_label=X['trainY'][0] 
data_label=data_label.astype('int32')
#counter=0
print(data_label[1])
zit=np.ones((10,10))
print(zit)

(60000, 784)
0
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [193]:
#This determines all the pixels that are not important so it can be turned into the 494 sized vector

def preprocess(training_set):
    num_rows, num_cols=training_set.shape
    print(num_rows)
    print(num_cols)
    list_of_pixels=[0]*num_cols
    print(len(list_of_pixels))
    modified_set=training_set
    
    for col in range(num_cols):
        counter=0
        for row in range(num_rows):
            if(training_set[row][col]!=0):
                counter=counter+1
            if(counter==600):
                list_of_pixels[col]=col #2 means safe
                row=59999
    for i in range(len(list_of_pixels)):
        if(list_of_pixels[i]==2):
            counter=counter+1#make counter and an empty array and whenever I run into something I want to save use the counter to copy that index over to empty array, but it only works for size 494 hmm
            #np.delete(modified_set,list_of_pixels,1)
            
    return list_of_pixels
reduced_training_data=preprocess(data_train)
print(reduced_training_data)

                

60000
784
784
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 68, 69, 70, 71, 72, 73, 74, 75, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 0, 0, 0, 0, 0, 0, 0, 0, 0, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 0, 0, 0, 0, 0, 0, 0, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 0, 0, 0, 0, 0, 0, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 0, 0, 0, 0, 0, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249

In [289]:
test_train=X['testX']
test_label=X['testY'][0]
counter=0
test_data=test_train
reduced_test_data=preprocess(test_train)
#This actually deletes the pixels that are not important
for i in range(784):
    if(reduced_test_data[i] == 0):
        test_data=np.delete(test_data,i-counter,1)
        counter=counter+1
test_train=test_data   #this is the reduced test data
print(test_train.shape) 
print(counter)

10000
784
784
(10000, 380)
404


In [293]:
test_train=X['testX']
test_label=X['testY'][0]
counter=0
copy_data=data_train
for i in range(784):
    if(reduced_training_data[i] == 0):
        copy_data=np.delete(copy_data,i-counter,1)
        test_train=np.delete(test_train,i-counter,1)
        counter=counter+1
print(copy_data.shape)
print(test_train.shape)
print(counter)
#Same as above but for training data

(60000, 493)
(10000, 493)
291


In [195]:
#This processes the label so that all the data labels that dont correspond to number 1 or 2 are deleted and makes data label of 
#number 1, 1 and the data_label of number 2 negative 2
def Data_Label_Processing(Number_1,Number_2,label_set):
    counter=0
    Number_1_counter=0
    Number_2_counter=0
    copy_label=label_set
    size=len(copy_label)
    for i in range(size):
                    if (copy_label[i-counter]==Number_1):
                        copy_label[i-counter]=1
                        continue
                    if(copy_label[i-counter]==Number_2):
                        copy_label[i-counter]=-1
                        continue
                    else:
                        copy_label=np.delete(copy_label,i-counter,0)
                        counter=counter+1
    return copy_label

classified_label_set=Data_Label_Processing(0,5,data_label)
print(classified_label_set)
print(classified_label_set.size)
            
 #return a 45 sized array plz           

    

[-1  1 -1 ...  1 -1 -1]
11344


In [196]:
complete_classified_label_set=[None]*45  #where all my classified and transformed labels are now
label_classify_counter=0
for i in range(9):
    for j in range(10):
        if(j>i):
            complete_classified_label_set[label_classify_counter]=Data_Label_Processing(i,j,data_label)
            print('Done', complete_classified_label_set[label_classify_counter].shape)
            print(i,j)
            label_classify_counter=label_classify_counter+1

Done (12665,)
0 1
Done (11880,)
0 2
Done (12053,)
0 3
Done (11764,)
0 4
Done (11342,)
0 5
Done (11840,)
0 6
Done (12187,)
0 7
Done (11773,)
0 8
Done (11871,)
0 9
Done (12701,)
1 2
Done (12874,)
1 3
Done (12585,)
1 4
Done (12163,)
1 5
Done (12661,)
1 6
Done (13008,)
1 7
Done (12594,)
1 8
Done (12692,)
1 9
Done (12089,)
2 3
Done (11800,)
2 4
Done (11378,)
2 5
Done (11876,)
2 6
Done (12223,)
2 7
Done (11809,)
2 8
Done (11907,)
2 9
Done (11973,)
3 4
Done (11551,)
3 5
Done (12049,)
3 6
Done (12396,)
3 7
Done (11982,)
3 8
Done (12080,)
3 9
Done (11262,)
4 5
Done (11760,)
4 6
Done (12107,)
4 7
Done (11693,)
4 8
Done (11791,)
4 9
Done (11338,)
5 6
Done (11685,)
5 7
Done (11271,)
5 8
Done (11369,)
5 9
Done (12183,)
6 7
Done (11769,)
6 8
Done (11867,)
6 9
Done (12116,)
7 8
Done (12214,)
7 9
Done (11800,)
8 9


In [197]:

def Data_Train_Process(Number_1,Number_2,training_set,label_set):
    where_counter=0
    index_incrementor=0
    num_rows, num_cols=training_set.shape
    #print(num_rows)
    for mover in range(num_rows):
        #print('mover is',mover)
        #print(label_set[mover])
        if(label_set[mover]==Number_1 or label_set[mover]==Number_2):
            where_counter=where_counter+1
    modified_training=np.ones((where_counter,493))
    for mover in range(num_rows): 
        if(label_set[mover]==Number_1 or label_set[mover]==Number_2): 
            modified_training[index_incrementor][:]=np.where(label_set[mover]==Number_1 or label_set[mover]==Number_2, training_set[mover][:], label_set[mover])
            index_incrementor=index_incrementor+1
        #print('modified_training is',modified_training)
        #print(type(item))
        #print(item[1])
    print(index_incrementor)
    return modified_training
hi=Data_Train_Process(0,1,copy_data,data_label)
print(hi.shape)


12665
(12665, 493)


In [198]:
Processed_Training_Data=[None]*45
Data_Train_Process_Counter=0
for i in range(9):
    for j in range(10):
        if(j>i):
            Processed_Training_Data[Data_Train_Process_Counter]=Data_Train_Process(i,j,copy_data,data_label)
            Data_Train_Process_Counter=Data_Train_Process_Counter+1
            print(i,j)
#Does the function above


12665
0 1
11880
0 2
12053
0 3
11764
0 4
11342
0 5
11840
0 6
12187
0 7
11773
0 8
11871
0 9
12701
1 2
12874
1 3
12585
1 4
12163
1 5
12661
1 6
13008
1 7
12594
1 8
12692
1 9
12089
2 3
11800
2 4
11378
2 5
11876
2 6
12223
2 7
11809
2 8
11907
2 9
11973
3 4
11551
3 5
12049
3 6
12396
3 7
11982
3 8
12080
3 9
11262
4 5
11760
4 6
12107
4 7
11693
4 8
11791
4 9
11338
5 6
11685
5 7
11271
5 8
11369
5 9
12183
6 7
11769
6 8
11867
6 9
12116
7 8
12214
7 9
11800
8 9


In [220]:
print(Processed_Training_Data[1])
a=Processed_Training_Data
print(a[1][1])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.  93. 164. 211. 250. 250. 194.  15.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.  20. 176. 253. 237. 180. 180.
 243. 254. 214.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0. 204. 236. 135.  18.   0.   0.  40. 242. 252. 126.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  69. 253. 167.   0.
   0.   0.   0.   0. 130. 254. 223.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.  74. 217.  79.   0.   0.   0.   0.   0.  46.
 254. 231.  14.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   8.  10.   0.   0.   0.   0.   0.   0.  39. 254. 254. 104.   

In [208]:
# dont run again it takes close to half an hour and randomly stops
def Least_Squares(processed_training,processed_label):
    theta=[None]*45
    for i in range(45):
        counter=0
        row_num, col_num=processed_training[i].shape
        Temp_Train=processed_training[i]
        constant_training=np.ones((row_num,1)).reshape(row_num,1)
        Temp_Train=np.hstack((constant_training,processed_training[i]))
        print(Temp_Train.shape)

        theta_inside=(Temp_Train.transpose()).dot(Temp_Train)
        theta[i]=np.linalg.pinv(theta_inside)
        theta[i]=theta[i].dot(Temp_Train.transpose())
        theta[i]=theta[i].dot(processed_label[i])
        print(i)
    #print("data label is ",data_label)
    #print(theta)
    #print(Temp_Train.shape)
    #print(Temp_Train)
    return(theta)
#Theta_One_For_One=Least_Squares(Processed_Training_Data,complete_classified_label_set)


TypeError: list indices must be integers or slices, not tuple

In [260]:
# Now I actually run the classifier
def One_To_One(test_set,theta_given,Number_1,Number_2,data_label_were_looking_at):
    if(Number_1==0 and Number_2==1):
        number_in_theta=0
    if(Number_1==0 and Number_2==2):
        number_in_theta=1
    if(Number_1==0 and Number_2==3):
        number_in_theta=2
    if(Number_1==0 and Number_2==4):
        number_in_theta=3
    if(Number_1==0 and Number_2==5):
        number_in_theta=4
    if(Number_1==0 and Number_2==6):
        number_in_theta=5
    if(Number_1==0 and Number_2==7):
        number_in_theta=6
    if(Number_1==0 and Number_2==8):
        number_in_theta=7
    if(Number_1==0 and Number_2==9):
        number_in_theta=8
    if(Number_1==1 and Number_2==2):
        number_in_theta=9
    if(Number_1==1 and Number_2==3):
        number_in_theta=10
    if(Number_1==1 and Number_2==4):
        number_in_theta=11
    if(Number_1==1 and Number_2==5):
        number_in_theta=12
    if(Number_1==1 and Number_2==6):
        number_in_theta=13
    if(Number_1==1 and Number_2==7):
        number_in_theta=14
    if(Number_1==1 and Number_2==8):
        number_in_theta=15
    if(Number_1==1 and Number_2==9):
        number_in_theta=16
    if(Number_1==2 and Number_2==3):
        number_in_theta=17
    if(Number_1==2 and Number_2==4):
        number_in_theta=18
    if(Number_1==2 and Number_2==5):
        number_in_theta=19
    if(Number_1==2 and Number_2==6):
        number_in_theta=20
    if(Number_1==2 and Number_2==7):
        number_in_theta=21
    if(Number_1==2 and Number_2==8):
        number_in_theta=22
    if(Number_1==2 and Number_2==9):
        number_in_theta=23
    if(Number_1==3 and Number_2==4):
        number_in_theta=24
    if(Number_1==3 and Number_2==5):
        number_in_theta=25
    if(Number_1==3 and Number_2==6):
        number_in_theta=26
    if(Number_1==3 and Number_2==7):
        number_in_theta=27
    if(Number_1==3 and Number_2==8):
        number_in_theta=28
    if(Number_1==3 and Number_2==9):
        number_in_theta=29
    if(Number_1==4 and Number_2==5):
        number_in_theta=30
    if(Number_1==4 and Number_2==6):
        number_in_theta=31
    if(Number_1==4 and Number_2==7):
        number_in_theta=32
    if(Number_1==4 and Number_2==8):
        number_in_theta=33
    if(Number_1==4 and Number_2==9):
        number_in_theta=34
    if(Number_1==5 and Number_2==6):
        number_in_theta=35
    if(Number_1==5 and Number_2==7):
        number_in_theta=36
    if(Number_1==5 and Number_2==8):
        number_in_theta=37
    if(Number_1==5 and Number_2==9):
        number_in_theta=38
    if(Number_1==6 and Number_2==7):
        number_in_theta=39
    if(Number_1==6 and Number_2==8):
        number_in_theta=40
    if(Number_1==6 and Number_2==9):
        number_in_theta=41
    if(Number_1==7 and Number_2==8):
        number_in_theta=42
    if(Number_1==7 and Number_2==9):
        number_in_theta=43
    if(Number_1==8 and Number_2==9):
        number_in_theta=44
    theta_guess=theta_given[number_in_theta]
    alpha=theta_guess[0]
    Actual_Theta=theta_guess[1:]
    #unpack=test_set[number_in_theta]
    #print('size is',alpha)
    #print('shape of att is', (Actual_Theta.transpose()).shape)
    #print('shape of unpack is',unpack)
    #temp_theta=(Actual_Theta.transpose()).dot(unpack[data_label_were_looking_at])
    temp_theta=alpha+(Actual_Theta.transpose()).dot(test_set[data_label_were_looking_at,:])
    #print('temp_theta', temp_theta.shape)
    Classifier=alpha+temp_theta
    #print(Classifier.shape)
    if(Classifier>=0):
        return 1
    else:
        return -1
#print(type(Processed_Training_Data)) 
#chief=One_To_One(Processed_Training_Data,Theta_One_For_One,5,8,0)
chief=One_To_One(copy_data,Theta_One_For_One,2,5,-3) #use copy_data for testing 

print(chief)

-1


In [277]:
#combines everything and completes the one to one, and returns what number that corresponding image is
def One_To_One_Complete(test_set,theta_given,label_number):
    #for testing training error
    vote=[0]*10
    temp_digit=0
    temp_counter=0
    big_counter=0
    for i in range(10):
        for j in range(10):
            if(j>i):
                answer=One_To_One(test_set,Theta_One_For_One,i,j,label_number)
                if(answer==1):
                    vote[i]=vote[i]+1
                else:
                    vote[j]=vote[j]+1
    for big_digit in vote:
        if big_digit>temp_digit:
            temp_digit=big_digit
            big_counter=temp_counter
        temp_counter=temp_counter+1
    #print(vote)    
    return big_counter 
One_To_One_Complete(copy_data,Theta_One_For_One,1)

0

In [295]:
#This prints the confusion matrix
checker_counter=0
confusion_matrix=np.zeros((10,10))
conf_col=0
for i in range(10000):
    checker=One_To_One_Complete(test_train,Theta_One_For_One,i)
    conf_col=test_label[i]
    confusion_matrix[conf_col][checker]=confusion_matrix[conf_col][checker]+1
    if(checker!=test_label[i]):
        checker_counter=checker_counter+1
print(checker_counter)
np.set_printoptions(suppress=True)
print(confusion_matrix)

1169
[[ 951.    0.    1.    1.    0.   20.    2.    4.    0.    1.]
 [   0. 1103.    5.    5.    1.   15.    1.    4.    1.    0.]
 [   7.    6.  960.    4.   11.   21.    7.   13.    3.    0.]
 [   9.    0.   35.  801.    0.  137.    0.   20.    4.    4.]
 [   1.    0.    8.    1.  933.   13.    1.   14.    1.   10.]
 [   4.    0.    2.    7.    2.  867.    6.    3.    0.    1.]
 [  10.    3.   22.    1.   16.   65.  840.    1.    0.    0.]
 [   1.    4.   17.    2.    6.    6.    0.  985.    0.    7.]
 [   8.   18.   31.   30.   24.  262.    4.   21.  559.   17.]
 [   4.    2.    1.    3.   70.   33.    0.   63.    1.  832.]]
